### ISSUE TITLE
Windows CI build stops at `cinst` not being a command, in Ruby 3.0

### ISSUE THREAD

**Issue by olleolleolle** [janlelis/paint#36]
From a CI run:
```
Run cinst ansicon
cinst: D:\a\_temp\d1a0e82b-8211-4346-a1a2-1fbf8a380653.ps1:2
Line |
   2 |  cinst ansicon
     |  ~~~~~
     | The term 'cinst' is not recognized as a name of a cmdlet, function, script file, or executable program. Check
     | the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by olleolleolle** [comment]
Does it need to install Chocolatey or something? https://github.com/marketplace/actions/chocolatey-action

**Comment by olleolleolle** [comment]
@janlelis Perhaps

```yaml
   -
        name: Choco help
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install ansicon
```
